### ISSUE TITLE
How does the billing page work?

### ISSUE THREAD

**Issue by TWSICommunity** [greyhavens/msoy#30]
I noticed in my test instance when I brought back the bars and such I notice the #billing page. What does it do and is it useless? I was just wondering because I saw under billing.whirled.com/#billing. Should I change that to my own url?

**Comment by Shadowsych** [comment]
The billing page is no longer available. It was the page players could purchase bars and club whirled with, and it seems Three Rings used the billing.whirled domain for it instead of the standard whirled.com domain. 

The billing.whirled domain must've been a separate web-application from the msoy project, so that's why it's not available.

TL;DR: you need to create your own webpage for the billing webpage

**Comment by TWSICommunity** [comment]
Oh I see. well I guess that solves that then...
